### ISSUE TITLE
Using pre-computed BAM files? Trouble installing on Linux cluster but works okay on Mac

### ISSUE THREAD

**Issue by pierrj** [njaupan/ECDNA#13]
Hello,

I am having some trouble creating the conda env on my university's cluster (running Scientific Linux 7.9) but was able to create the environment on my Mac no problem. However, the cluster obviously performs much better than the Mac.

Would it be possible for me to provide ecc_finder with BAM files by properly setting up the file structure? If so could you please describe how to do so? I am assuming the mapping step is by far the most time consuming in the pipeline so it would be great to do this on the cluster.

Thanks,
Pierre

**Comment by njaupan** [comment]
Hi Pierre, I am now updating the installation to the servers and will come back to you soon!
Best

**Comment by pierrj** [comment]
Thank you!

**Comment by pierrj** [comment]
To answer my original question, yes it is possible to use previously computed map files. Here is what I did:
```
fastp --thread ${SLURM_NTASKS} -i $READ_ONE \
             -I $READ_TWO \
             -o ecc.sr.R1.fastq.gz \
             -O ecc.sr.R2.fastq.gz \
             -h ecc.sr.html

bwa mem -t $THREADS ${genome} \
            ecc.sr.R1.fastq.gz \
            ecc.sr.R2.fastq.gz > ecc.sr.sam 2> ecc.sr.sam.log
```

Then I transferred all of the resulting files to a subdirectory called align_files within the ecc_finder output directory and the scripts ran without any issue without needing to remap.

**Comment by pierrj** [comment]
As for getting ecc_finder to run on my cluster, here is the conda command I used to get it to work, assuming the proper channels are set up

```
conda install -y python=3.8.5 pysam=0.17.0 pandas=1.3.3 pybedtools=0.8.2 numpy=1.21 matplotlib=3.4.3 bwa=0.7.17 fastp=0.22.0 genrich=0.6.1 seqtk=1.3
```
